# Site
name: "The Good | Bad Picture"
title: "The Good | Bad Picture"
description: "Hi,I remake drawings from online to offline world with my hands."
logo: 'assets/images/tgbp.png'
favicon: 'assets/images/tgbp.png'
baseurl: 
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'thegoodbadpicture'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: badd_drawings@gmail.com

# Authors
authors:
  ad:
    name: Ad
    display_name: Ad
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: adarsh.agrahari26@gmail.com
    web: www.github.com/sir-ad
    instagram: https://instagram.com/stan.ad/
    description: "Data Scientist"
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
